version: "3.6"
services:
  mongodb:
    image: 'mongo:3.4.9'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db
    environment:
      MONGO_INITDB_DATABASE: VisitorManagement
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
  backend:
    build: .
    container_name: backend
    ports:
      - '8080:8080'
    # volumes:
    #   - logs:/app/logs
    environment:
      MONGODB_USERNAME: admin
      MONGODB_PASSWORD: password
    depends_on:
      - mongodb

volumes:
  data:
  # logs: