app:
    mail-personal: ${MAIL_PERSONAL:z-visitor}
    #employee sync cron job expression
    #It will sync employee detatils from slack channel over the configured period.
    emp-sync-job: 0 0 10 * * *
    admin-email: ${ADMIN_MAIL:default-administrator}
    admin-password: ${ADMIN_PASSWORD:default-password}
    secretKey: ${SECRET_KEY:31323334353637383930313233343536}
    slack:
      #This slack token will be used for send slack notification.
      token: ${SLACK_TOKEN:token}
      # username should start with @ EX: @Virtual Receptionist
      user-name: ${SLACK_USERNAME:slack-user-account-username}
    config:
      file-uploads-path: ${FILE_UPLOAD:files}
    #visitor origin categories
    visitor-category:
        Bank Finance Support: bank-finance
        Client Visit : client-visit
        Interview : interview
        Personal Meet : personal-meet    
        Technical Support : technical-support
        Other : other
    org:  
        #app employees validity  EX: 
        #EX:   
        #- zymrinc.com
        #- zymr.com
        valid-email-domains: ${VALID_MAIL:zymr.com}
        #app departments/slack group. Sholud be in below format.
        department:
        - 
           slackid: ${ORG_DEPARTMENT_SLACK_ID:C1LFAPHB9}
           email: ${ORG_DEPARTMENT_EMAIL:org_department_email}
        #EX:   
        #-
          #slackid: G5FPQRSR5
          #email: test@gmail.com
        #-
          #slackid: G5JL8AWJX
          #email: test2@gmail.com
        #-
          #slackid: G06ADQESB
          #email: test3@gmail.com   
        locations:
        - 
           abbr: ${ORG_LOCATION_ABBR:z2}
           slackid: ${ORG_LOCATION_SLACK_ID:C1LFAPHB9}
           name: ${ORG_LOCATION_SLACK_NAME:Ahmedabad}
        #EX:   
        #-
          #abbr: z2
          #slackid: CDKRHYRHB9
          #name: Ahmedabad
        #-
          #abbr: z3
          #slackid: C1LAWEMDKR
          #name: Pune
spring:
  data:
    mongodb:
      database: ${MONGODB_DATABASE:VisitorManagement}
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      username: ${MONGODB_USERNAME:admin}
      password: ${MONGODB_PASSWORD:password}
      authentication-database: ${AUTHENTICATION_DATABASE:admin}
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB      
  mail:
    host: smtp.gmail.com
    port: 587
    #This email id will be used to send application emails.
    username: ${MAIL_USERNAME:email-id}
    password: ${MAIL_PASSWORD:email-password}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#server configuration
server:
  port: ${USER_APP_PORT:8080}