app:
    mail-personal: prerana.dabhade@zymr.com
    #employee sync cron job expression
    #It will sync employee detatils from slack channel over the configured period.
    emp-sync-job: 0 0 10 * * *
    admin-email: prerana.dabhade@zymr.com
    admin-password: SouSweet
    secretKey: 12345678
    slack:
      #This slack token will be used for send slack notification.
      token: abc
      # username should start with @ EX: @Virtual Receptionist
      user-name: preranadabhade
    config:
      file-uploads-path: C:\visitors-files
    #visitor origin categories
    visitor-category:
        Bank Finance Support: bank-finance
        Client Visit : client-visit
        Interview : interview
        Personal Meet : personal-meet    
        Technical Support : technical-support
        Other : other
    org:  
        #app employees validity  EX: 
        #EX:   
        #- zymrinc.com
        #- zymr.com
        valid-email-domains: prerana.dabhade@zymr.com
        #app departments/slack group. Sholud be in below format.
        department:
        - 
           slackid: <slack-group1-slackid>
           email: prerana.dabhade@zymr.com
        #EX:   
        #-
          #slackid: G5FPQRSR5
          #email: test@gmail.com
        #-
          #slackid: G5JL8AWJX
          #email: test2@gmail.com
        #-
          #slackid: G06ADQESB
          #email: test3@gmail.com   
        locations:
        - 
           abbr: z2
           slackid: CDKRHYRHB9
           name: Ahmedabad
        #EX:   
        #-
          #abbr: z2
          #slackid: CDKRHYRHB9
          #name: Ahmedabad
        #-
          #abbr: z3
          #slackid: C1LAWEMDKR
          #name: Pune
spring:
  data:
    mongodb:
#      uri: mongodb://admin:password@mongodb:27017/VisitorManagement
      database: VisitorManagement
      host: mongodb
      #<database-server-port> EX: 27017
      port: 27017
      username: admin
      password: password
#      uri:  mongodb://host:27017/VisitorManagement
      authentication-database: admin
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB      
  mail:
    host: smtp.gmail.com
    port: 587
    #This email id will be used to send application emails.
    username: prerana.dabhade@gmail.com
    password: SouSweet
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#server configuration
server:
  # address: localhost
  port: 8080