app:
    mail-personal: <mail-from-personal>
    #employee sync cron job expression
    #It will sync employee detatils from slack channel over the configured period.
    emp-sync-job: 0 0 10 * * *
    admin-email: <default-administrator>
    admin-password: <default-password>
    secretKey: <secret-key>
    slack:
      #This slack token will be used for send slack notification.
      token: <slack-user-account-token>
      # username should start with @ EX: @Virtual Receptionist
      user-name: <slack-user-account-username>
    config:
      file-uploads-path: <file-base-dir-name>
    #visitor origin categories
    visitor-category:
        Bank Finance Support: bank-finance
        Client Visit : client-visit
        Interview : interview
        Personal Meet : personal-meet    
        Technical Support : technical-support
        Other : other
    org:  
        #app employees validity  EX: 
        #EX:   
        #- zymrinc.com
        #- zymr.com
        valid-email-domains: <valid-email-domains>
        #app departments/slack group. Sholud be in below format.
        department:
        - 
           slackid: <slack-group1-slackid>
           email: <slack-group1-email>
        #EX:   
        #-
          #slackid: G5FPQRSR5
          #email: test@gmail.com
        #-
          #slackid: G5JL8AWJX
          #email: test2@gmail.com
        #-
          #slackid: G06ADQESB
          #email: test3@gmail.com   
        locations:
        - 
           abbr: <location-abbreviation>
           slackid: <slack-channel-id>
           name: <location-name>
        #EX:   
        #-
          #abbr: z2
          #slackid: CDKRHYRHB9
          #name: Ahmedabad
        #-
          #abbr: z3
          #slackid: C1LAWEMDKR
          #name: Pune
spring:
  data:
    mongodb:
      database: <database-name>
      host: <database-server-host>
      #<database-server-port> EX: 27017
      port: 27017
      username: <database-username>
      password: <database-password>
      authentication-database: <authentication-database-name>
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB      
  mail:
    host: smtp.gmail.com
    port: 587
    #This email id will be used to send application emails.
    username: <email-id>
    password: <email-password>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
#server configuration
server:
  address: <server-host>